version: 2
updates:
  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  
  # pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
