name: Tests
on:
  workflow_dispatch:

jobs:
  tests:
    name: All tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt && pip install -e .
      - name: Run type checker
        run: |
          mypy
      - name: Run linter
        run: |
          flake8 src/semver
      - name: Run unit tests
        run: |
          pytest
